version: "3"
services:
  db:
    image: "postgres:latest"
    restart: always
    environment:
      - POSTGRES_DB=$DATABASE_NAME
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - PGPORT=$DATABASE_PORT
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - "./db-data:/var/lib/postgresql/data"
    ports:
      - "$DATABASE_PORT:$DATABASE_PORT"

volumes:
  db-data:
